fix: Cannot find module '@cheap-glitch/mi-cron'
Latest version is throwing a module not found error:

```
Error: Cannot find module '@cheap-glitch/mi-cron'
Require stack:
- /home/circleci/.npm/_npx/876/lib/node_modules/renovate/dist/workers/branch/schedule.js
- /home/circleci/.npm/_npx/876/lib/node_modules/renovate/dist/config/validation.js
- /home/circleci/.npm/_npx/876/lib/node_modules/renovate/dist/config-validator.js
```