fix(deps): fix invalid named exports
Node v22.18.0 now flags invalid named exports, such as:

```
renovate/lib/modules/manager/bazel-module/extract.ts:1
import { dirname } from 'upath';
         ^

SyntaxError: The requested module 'upath' does not provide an export named 'dirname'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:228:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:335:5)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:647:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:117:5)
```

This issue here is that `upath` has a `dirname` function, but it's only
available on the default export, not as a named export.

Fix all the cases that cause `pnpm build` to fail.

Relates to https://github.com/renovatebot/renovate/discussions/37321