build: ignore Git worktrees from build/test tooling
This is a similar change to 81a621a570a0890724174d560bb6f742821f677a,
but applies to our Vitest, Eslint and Typescript build configuration.

Without this, `pnpm run test` may fail with:

```
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
...
```